macro(opener_platform_spec)
  include_directories(${PORTS_SRC_DIR}/${OpENer_PLATFORM} ${PORTS_SRC_DIR}/${OpENer_PLATFORM}/sample_application)
  set(OPENER_NETBURNER_LWIP_INCLUDE_DIR "" CACHE PATH "Path to lwIP headers for NetBurner platform")
  if(OPENER_NETBURNER_LWIP_INCLUDE_DIR)
    include_directories(${OPENER_NETBURNER_LWIP_INCLUDE_DIR})
  elseif(NOT OPENER_EMBEDDED_PORT_DRY_RUN)
    message(FATAL_ERROR "NetBurner platform currently reuses the ClearCore/lwIP port layer. Set OPENER_NETBURNER_LWIP_INCLUDE_DIR or enable OPENER_EMBEDDED_PORT_DRY_RUN for host-only configure checks.")
  endif()
  if(MSVC)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /D_CRT_SECURE_NO_WARNINGS")
  else()
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99 -Werror=implicit-function-declaration -fcommon")
  endif()
  if(NOT CMAKE_INSTALL_LIBDIR)
    set(CMAKE_INSTALL_LIBDIR "lib")
  endif()
  if(NOT CMAKE_INSTALL_INCLUDEDIR )
    set(CMAKE_INSTALL_INCLUDEDIR "include")
  endif()
  add_definitions(-D_GNU_SOURCE -DNETBURNER -DCLEARCORE)
  get_property(languages GLOBAL PROPERTY ENABLED_LANGUAGES)
  if ("CXX" IN_LIST languages)
    add_definitions(-DRESTRICT=)
  else()
    add_definitions(-DRESTRICT=restrict)
  endif()
endmacro(opener_platform_spec)
